# Generated by Django 2.2.3 on 2019-08-27 05:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('proj_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('Git_repo', models.CharField(blank=True, max_length=200)),
                ('Title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('Employee_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.Experience')),
            ],
        ),
    ]
