# Generated by Django 2.2.3 on 2019-08-28 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='Skill_used',
            field=models.CharField(default='xsl', max_length=100),
        ),
    ]
