# Generated by Django 2.2.3 on 2019-09-02 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_projects_skill_used'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='Git_repo',
            field=models.CharField(blank=True, default=None, max_length=200),
        ),
    ]
