# Generated by Django 2.2.3 on 2019-09-02 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_auto_20190902_1516'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='Git_repo',
            field=models.CharField(blank=True, default='copyright', max_length=200),
        ),
    ]
