# Generated by Django 2.2.3 on 2019-08-27 05:36

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Academic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('College', models.CharField(max_length=200)),
                ('Course', models.CharField(max_length=200)),
                ('Specialization', models.CharField(max_length=200)),
                ('From', models.DateField(blank=True)),
                ('To', models.DateField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=50)),
                ('message', models.TextField(blank=True)),
                ('Contact_date', models.DateField(blank=True, default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='PersonalDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200)),
                ('Gender', models.CharField(max_length=100)),
                ('Age', models.IntegerField()),
                ('Interest', models.CharField(max_length=200)),
                ('Passport', models.CharField(max_length=200)),
                ('E_Mail', models.CharField(max_length=50)),
                ('DOB', models.DateField(blank=True)),
                ('Linkedin', models.CharField(max_length=200)),
                ('skype', models.CharField(max_length=200)),
                ('facebook', models.CharField(max_length=200)),
                ('git', models.CharField(max_length=200)),
                ('Primary_contacts', models.CharField(max_length=20)),
                ('Secondary_contacts', models.CharField(max_length=20)),
                ('Maritial_Status', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Skillsets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Skill', models.CharField(max_length=200)),
                ('Proficiency_Percentage', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('Employee_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('Company', models.CharField(max_length=200)),
                ('Logo', models.ImageField(blank=True, upload_to='companyLogo/')),
                ('From', models.DateField(default=datetime.date.today)),
                ('To', models.DateField(blank=True)),
                ('NoticePeriod', models.IntegerField()),
                ('ServingNotice', models.BooleanField(default=False)),
                ('Person_ID', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.PersonalDetails')),
            ],
        ),
    ]
