# Generated by Django 2.2.3 on 2019-08-28 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='Designation',
            field=models.CharField(default='Software Engineer', max_length=100),
        ),
    ]
