# Generated by Django 2.2.3 on 2019-08-28 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_experience_designation'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='Location',
            field=models.CharField(default='India', max_length=100),
        ),
    ]
