# Generated by Django 2.2.3 on 2019-08-28 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_experience_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='academic',
            name='Location',
            field=models.CharField(default='Mumbai, India', max_length=200),
        ),
    ]
