# Generated by Django 2.2.3 on 2019-08-28 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_academic_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='personaldetails',
            name='Address',
            field=models.TextField(default='india'),
        ),
    ]
