# Generated by Django 2.2.3 on 2019-08-28 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_personaldetails_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='personaldetails',
            name='About_me',
            field=models.TextField(default='Developer with diverse Experice'),
        ),
    ]
