# Generated by Django 2.2.3 on 2019-08-28 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_personaldetails_about_me'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='To',
            field=models.DateField(blank=True, null=True),
        ),
    ]
