# Generated by Django 2.2.3 on 2019-08-29 04:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20190828_1603'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academic',
            name='To',
            field=models.DateField(blank=True, default=datetime.date.today, null=True),
        ),
    ]
