# Generated by Django 2.2.3 on 2019-09-20 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20190902_2042'),
    ]

    operations = [
        migrations.AddField(
            model_name='personaldetails',
            name='Cv',
            field=models.FileField(default='upload/CV/CV.pdf', upload_to='uploads/CV/'),
        ),
    ]
