# Generated by Django 2.2.3 on 2019-10-05 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_personaldetails_cv'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='startOfNotice',
            field=models.DateField(blank=True, null=True),
        ),
    ]
