# Generated by Django 2.2.3 on 2019-10-07 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_experience_startofnotice'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='endOfNotice',
            field=models.DateField(blank=True, null=True),
        ),
    ]
