# Generated by Django 2.2.3 on 2019-10-09 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_experience_endofnotice'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='visible',
            field=models.BooleanField(default=False),
        ),
    ]
