# Generated by Django 2.2.3 on 2019-10-09 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_experience_visible'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='visible',
            field=models.BooleanField(default=True),
        ),
    ]
