# Generated by Django 2.2.3 on 2019-10-09 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_auto_20191009_2059'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experience',
            name='startOfNotice',
        ),
    ]
